### ISSUE TITLE
Support for Optional Arguments

### ISSUE THREAD

**Issue by jwmach1** [MonsantoCo/mocka#18]
I took this example below from your readme, with small tweaks to use require/assert.  The first one is for illustration, the second test fails.

I don't see anything in the README that optional arguments are explicitly not supported. The generated gRPC service client always has an `opts ...grpc.CallOption` as the last argument, so the use case is typical to mock out the call to the service method.

The test below gives me this output:
```
test.run "^Test_AsShownInReadme|Test_WithOptional$" #gosetup
=== RUN   Test_AsShownInReadme
--- PASS: Test_AsShownInReadme (0.00s)
=== RUN   Test_WithOptional
    Test_WithOptional: mocka_optional_test.go:36: 
        	Error Trace:	mocka_optional_test.go:36
        	Error:      	Received unexpected error:
        	            	mocka: stub does not exist
        	Test:       	Test_WithOptional
--- FAIL: Test_WithOptional (0.00s)
FAIL

Process finished with exit code 1
```

```golang
package step_test

import (
	"testing"

	"github.com/MonsantoCo/mocka"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_AsShownInReadme(t *testing.T) {
	var fn = func(str string) int {
		return len(str)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123").Return(5))

	assert.Equal(t, 5, fn("123"))
}

func Test_WithOptional(t *testing.T) {
	var fn = func(str string, opts ...string) int {
		return len(str) + len(opts)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123").Return(5))

	assert.Equal(t, 5, fn("123"))
}
```

**Comment by jwmach1** [comment]
This might be straight forward to implement as I spike it out.

**Comment by cmarfia** [comment]
@jwmach1 thanks for the issue 👍.

I believe this might be related to issue #17.

In your opinion:

1. Would you expect arguments not provided, in this case the variadic one, to default to match any value supplied to the argument or match only no values supplied?

2. Would you expect to be able to omit other arguments that are not variadic? For example given `func(a, b, c, d string)` would you expect that you could only supply the values for `a` and `b`.

While we talk through this, here is a way you can get mocka to work with variadic functions.

1. Supply the value for the variadic argument (`nil` is the default for not supplied).
2. Use the [matcher package](https://github.com/MonsantoCo/mocka/blob/master/MATCH.MD#elements-containing) built into mocka for additional flexibility. 

Playground URL: https://play.golang.org/p/QoPtEa87-ur
```golang
package main

import (
	"testing"

	"github.com/MonsantoCo/mocka"
	"github.com/MonsantoCo/mocka/match"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_AsShownInReadme(t *testing.T) {
	var fn = func(str string) int {
		return len(str)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123").Return(5))

	assert.Equal(t, 5, fn("123"))
}

func Test_WithOptional(t *testing.T) {
	var fn = func(str string, opts ...string) int {
		return len(str) + len(opts)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123").Return(5))

	assert.Equal(t, 5, fn("123"))
}

func Test_WithOptional_ValueSupplied(t *testing.T) {
	var fn = func(str string, opts ...string) int {
		return len(str) + len(opts)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123", nil).Return(5))

	assert.Equal(t, 5, fn("123"))
}

func Test_WithOptional_UsingAnythingMatcher(t *testing.T) {
	var fn = func(str string, opts ...string) int {
		return len(str) + len(opts)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123", match.Anything()).Return(5))

	assert.Equal(t, 5, fn("123"))
}

func Test_WithOptional_UsingElementsContainingMatcher(t *testing.T) {
	var fn = func(str string, opts ...string) int {
		return len(str) + len(opts)
	}

	stub, err := mocka.Function(&fn, 20)
	require.NoError(t, err)
	defer stub.Restore()

	require.NoError(t, stub.WithArgs("123", match.ElementsContaining("A", "B")).Return(5))

	assert.Equal(t, 20, fn("123"))
	assert.Equal(t, 20, fn("123", "A"))
	assert.Equal(t, 5, fn("123", "A", "B", "C"))
}
```

**Comment by jwmach1** [comment]
to answer your questions: I would expect exact matching, and only the variadic is allowed to be not provided -- so matching only when no argument provided. Sure I could see setting the occasional specific value in the variadic argument: nil, empty slice, but most of the time it would just not be passed or be passed as specific values.

**Comment by cmarfia** [comment]
Looking at this more holistically I think there is definitely room for improvement. 

So the current behavior of `mocka` is as follows:

```golang
// No variadic arguments
_ = stub.WithArgs("123", nil).Return(5)

// Variadic arguments supplied
_ = stub.WithArgs("123", []string{"a", "b"}).Return(25)
```

Proposed Change
```golang
// No variadic arguments
_ = stub.WithArgs("123").Return(5)

// Variadic arguments supplied
_ = stub.WithArgs("123", "a", "b").Return(25)
```

This change will make stubbing variadic functions in `mocka` match how they are used by the language itself. 

However this change will be a breaking change to the API. I will probably group this change with issue #2 for a v2 release of mocka.  

The v2 release of mocka was next on my roadmap for this package.

Thoughts?

**Comment by jwmach1** [comment]
that proposed API is awesome!

**Comment by cmarfia** [comment]
I'll spike out the effort for this change and the other change soon. 

Should be able to provide an eta on when v2 will be published after that 😃

**Comment by cmarfia** [comment]
Wanted to provide an update.

This specific request:
- Document is complete
- Production code is complete
- Unit tests are in progress
- PR is in draft until unit tests are complete

After this feature is completed there is only one more keeping v2 of mock pending. Once that has been completed it will be released.

**Comment by cmarfia** [comment]
Will be release when issue #2 is completed

**Comment by cmarfia** [comment]
@jwmach1 **v2** has been released with these changes.

Check out the migration guide if you are looking to upgrade: https://github.com/MonsantoCo/mocka/blob/master/MIGRATE_TO_V2.md
