### ISSUE TITLE
mocka.Function: errors when stubbing a function with a directional channel

### ISSUE THREAD

**Issue by cmarfia** [MonsantoCo/mocka#5]
## Context /Problem
If the function you are stubbing has a direction channel as an argument or return value `mocka` will always fail to create the stub.

## How to Reproduce
```go
var _fn = func(c chan<- int) error {
    c <- 1
    return nil
}

// err = invalid type
_, err := mocka.Function(&_fn, nil)
```

## Proposed Solution
- [ ] Add check to cast channel's as directional channel types for the kind of channel.

**Comment by cmarfia** [comment]
@poost-frey, do you know how this can be reproduced?

The following test currently passes.
```go
func ExampleStub_ExecOnCall() {
	var fn = func(in <-chan int) <-chan int {
		out := make(chan int, 1)
		go func() {
			out <- <-in
		}()
		return out
	}

	out := make(chan int, 1)
	stub, err := mocka.Function(&fn, out)
	if err != nil {
		log.Fatal(err.Error())
	}
	defer stub.Restore()

	stub.ExecOnCall(func(args []interface{}) {
		c := args[0].(<-chan int)
		out <- <-c
	})

	in := make(chan int, 1)
	in <- 10
	o := fn(in)
	fmt.Println(<-o)
	// Output: 10
}
```

**Comment by poost-frey** [comment]
@cmarfia I think the issue I had with directional channels wasn't attributed to Mocka. If that test is passing, this issue is probably good to close for now.
